.TH MAP2 1
.SH NAME
Map2 \- A scripting language that allows complex key remapping on Linux.
.SH SYNOPSIS
\fBMap2\fR [FLAGS]
.SH FLAGS
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Prints verbose information

.TP
\fB\-d\fR, \fB\-\-devices\fR
Selects the input devices
.SH DEVICES
In order to capture device input it is necessary to configure which devices should get captured. A list of devices can be specified by providing a device list argument or by defining a default configuration in the user's configuration directory ($XDG_CONFIG_HOME/map2/device.list).


.SH LICENSE
MIT


.SH EXIT STATUS
.TP
\fB0\fR
Successful program execution.

.TP
\fB1\fR
Unsuccessful program execution.

.TP
\fB101\fR
The program panicked.
.SH EXAMPLES
.TP
run a script
\fB$ map2 example.m2\fR
.br
Runs the specified script.
.TP
run a script and capture devices matched by the device list
\fB$ map2 \-d device.list example.m2\fR
.br
Captures devices that match the selectors in `device.list` and runs the script.

.SH AUTHOR
.P
.RS 2
.nf
shiro <shiro@usagi.io>

